name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        deno: [stable]
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno (Unix) and check formatting
        if: |
          !startsWith(matrix.os, 'windows')
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $GITHUB_PATH
          deno fmt --check
      - name: Install Deno (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |-
          curl -fsSL https://deno.land/x/install/install.sh | sh
          echo "$HOME/.deno/bin" >> $env:GITHUB_PATH
      - name: Lint
        run: deno lint --unstable
